# This workflow will do a clean install of node dependencies, build the source code, run tests and publish to package to npmjs.com.

name: Publish

on:
  push:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  publish-npmjs:
    name: "Publish to npmjs"
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - name: Publish
      if: github.ref == 'refs/heads/master'
      uses: mikeal/merge-release@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  publish-gpr:
    name: "Publish to Github Packages"
    needs: publish-npmjs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        if: github.ref == 'refs/heads/master'
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}